server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    username: ${PRODUCT_DB_USERNAME}
    password: ${PRODUCT_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
